config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'posts#index' 

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
  

  resources :posts do  
  resources :comments
 end 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :user_id, presence: true
  belongs_to :user    
  validates :image, presence: true
  has_many :comments, dependent: :destroy
  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end  

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 } 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :avatar, styles: { medium: '152x152#' }  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/ 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

def create  
  @comment = @post.comments.build(comment_params)
  @comment.user_id = current_user.id

  if @comment.save
    flash[:success] = "Comment Successful!"
    redirect_to :back
  else
    flash[:alert] = "Check the comment form, something went wrong."
    render root_path
  end
end

def destroy  
  @comment = @post.comments.find(params[:id])

  @comment.destroy
  flash[:success] = "Comment deleted :("
  redirect_to root_path
end  

private

def comment_params  
  params.require(:comment).permit(:content)
end

def set_post  
  @post = Post.find(params[:post_id])
end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
  before_action :authenticate_user! 
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :owned_post, only: [:edit, :update, :destroy] 

  def index  
  @posts = Post.all.order('created_at DESC').page params[:page]
  end 

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed.  Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post  
  unless current_user == @post.user
    flash[:alert] = "That post doesn't belong to you!"
    redirect_to root_path
  end
end  
end  

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show 
  @user = User.find_by(user_name: params[:user_name]) 
  @posts = Post.all.order('created_at DESC').page params[:page]
end 
  def edit  
  @user = User.find_by(user_name: params[:user_name])
end 
  def update  
    @user = User.find_by(user_name: params[:user_name])
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

private

def profile_params  
  params.require(:user).permit(:avatar, :bio)
end  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper

	def alert_for(flash_type)  
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
end  
  def profile_avatar_select(user)  
  return image_tag user.avatar.url(:medium),
  id: 'image-preview',
  class: 'img-responsive img-circle profile-image' if user.avatar.exists?
  image_tag 'default-avatar.jpg', id: 'image-preview',
  class: 'img-responsive img-circle profile-image'
end  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comment.html.erb
<div id="comment">
  <div class="user-name">
    <%= comment.user.user_name %>
  </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do %>
      <span class="glyphicon glyphicon-remove delete-comment"></span>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "InstaTweet", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li>
      <%= link_to "New Post", new_post_path %>
    </li>
    <li>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </li>
  <% else %>
    <li>
      <%= link_to "Login", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Register", new_user_registration_path %>
    </li>
  <% end %>
  </ul>
    </div>
  </div>
</nav>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Exo+2:700' rel='stylesheet' type='text/css'>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstaTweet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Exo+2:700' rel='stylesheet' type='text/css'>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
  <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
      </div>


    
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
     <div id="drake"> 
      <div class="caption">
        <div class="user-names">
          <%= post.user.user_name %>....
          <%= post.caption %>
        </div>
      </div> 
        </div>
      <% if post.comments %>
        <% post.comments.each do |comment| %>
          <div class="comment">
            <div class="user-comments">
              <%= comment.user.user_name %>....     
              <%= comment.content %>
              <% if comment.user == current_user %>
              <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do %>
                <span id="jets" class="glyphicon glyphicon-remove delete-comment"></span>
              <% end %>
            <% end %>
            </div>
            <div class="comment-content">
      <% end %>
      <% end %>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <span id="rangers" class="glyphicon glyphicon-heart-empty"></span>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for [post, post.comments.build] do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
  <div class="text-center">
  <%= image_tag @post.image.url(:medium) %>
</div>
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div id="AROD" class="form-group text-center">
      <%= f.button :submit, class: 'btn-primary' %>
    </div>
  <% end %>
</div>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", posts_path %>
</div>

app/views/posts/form.html.erb
<%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
  <%= f.input :image %>
  <%= f.input :caption %>
  <%= f.button :submit %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-primary' %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
    |
    <%= link_to "Edit Post", edit_post_path(@post) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", root_path %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Change your profile image:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div id="knicks">
<% if @user == current_user %>
  <%= link_to '*Your Profile Needs an Update*', edit_profile_path(@user.user_name) %>
<% end %>
</div>

<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>